import type { Metadata } from "next";
import { Outfit, TASA_Orbiter, Jersey_20 } from "next/font/google";
import "./globals.css";
import HeaderWrapper from "@/components/header/HeaderWrapper";
import Footer from "@/components/footer/Footer";

const outfit = Outfit({
  preload: true,
  variable: "--font-outfit",
  subsets: ["latin"],
  fallback: ["sans-serif"],
});

const tasaOrbiter = TASA_Orbiter({
  preload: true,
  variable: "--font-tasa-orbiter",
  subsets: ["latin"],
  fallback: ["sans-serif"],
});

const jersey20 = Jersey_20({
  preload: true,
  variable: "--font-jersey-20",
  subsets: ["latin"],
  weight: "400",
  fallback: ["sans-serif"],
});

export const metadata: Metadata = {
  title: "Sirvelia",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${outfit.variable} ${tasaOrbiter.variable} ${jersey20.variable} antialiased flex flex-col min-h-screen`}
      >
        <HeaderWrapper />

        <main className="flex-1 flex flex-col bg-website-background bg-[url('/textures/bg-pattern.png')] bg-repeat bg-center bg-contain">
          {children}
        </main>

        <Footer />
      </body>
    </html>
  );
}
